name: tapak_jejak
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_crypto: ^2.0.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/LOGO.jpg
    - assets/banner_1.jpg
    - assets/banner_2.jpg
    - assets/banner_3.jpg
    - assets/profile.png
    - assets/eiger.jpg
    - assets/antarestar.jpg
    - assets/arei.jpg
    - assets/consina.jpg
    - assets/carumby.jpg
