name: tapak_jejak
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  intl: ^0.20.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  awesome_notifications: ^0.10.1
  flutter_compass: ^0.8.0
  google_generative_ai: ^0.4.6
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/LOGO.png
    - assets/marsha.png
    - assets/banner_1.jpg
    - assets/banner_2.jpg
    - assets/banner_3.jpg
    - assets/profile.png
    - assets/eiger.jpg
    - assets/antarestar.jpg
    - assets/arei.jpg
    - assets/consina.jpg
    - assets/carumby.jpg
    - assets/kosong.png
    - assets/comingsoon1.png
    - assets/tiket_masuk.png
    - assets/travel_ojek.png
    - assets/porter_guide.png
    - assets/sewa_alat.png
    - assets/private_open_trip.png
    - assets/camping_ground.png
    - assets/event.png
    - assets/event_background.png
    - assets/eat_stay.png
    - assets/keamanan.png
    - assets/cuaca.png
    - assets/blog.png
    - assets/tutorial.png
    - assets/tiket_masuk/
    - assets/antarestar/
    - assets/eiger/
    - assets/consina/
    - assets/arei/
    - assets/carumby/
    - assets/trip_kosong.png
    - assets/tidak_ada.png
    - assets/alat.jpg
    - assets/build.jpg
    - assets/FloraFauna.jpg
    - assets/kompas.jpg
    - assets/hiking.jpg
    - assets/p3.jpg
    - assets/packing.jpg
