org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Optimasi build performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.configureondemand=true

# Network optimization
org.gradle.vfs.watch=true
systemProp.http.socketTimeout=60000
systemProp.http.connectionTimeout=60000

# Incremental builds
android.enableR8.fullMode=false
android.enableD8=true
